---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    percona:
      server:
        includedir: '/etc/mysql/conf.d/'
        debian_username: 'root'
      yum:
        gpgcheck: false
      master: '192.168.0.21'
      slaves: ['192.168.0.22']

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]
  - name: centos-7.0
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[percona-multi::default]

  - name: master
    driver:
      vm_hostname: master-ubuntu14
      network:
      - ['private_network', {ip: '192.168.0.21'}]
    run_list:
    - recipe[percona-multi::master]
    excludes: ['ubuntu-12.04', 'centos-6.5', 'centos-7.0']
    attributes:
      percona:
        master: '192.168.0.21'
        slaves: ['192.168.0.22']

  - name: slave
    driver:
      vm_hostname: slave-ubuntu14
      network:
      - ['private_network', {ip: '192.168.0.22'}]
    run_list:
    - recipe[percona-multi::slave]
    excludes: ['ubuntu-12.04', 'centos-6.5', 'centos-7.0']
    attributes:
      percona:
        master: '192.168.0.21'
        slaves: ['192.168.0.22']

  - name: master
    driver:
      vm_hostname: master-ubuntu12
      network:
      - ['private_network', {ip: '192.168.0.23'}]
    run_list:
    - recipe[percona-multi::master]
    excludes: ['ubuntu-14.04', 'centos-6.5', 'centos-7.0']
    attributes:
      percona:
        master: '192.168.0.23'
        slaves: ['192.168.0.24']

  - name: slave
    driver:
      vm_hostname: slave-ubuntu12
      network:
      - ['private_network', {ip: '192.168.0.24'}]
    run_list:
    - recipe[percona-multi::slave]
    excludes: ['ubuntu-14.04', 'centos-6.5', 'centos-7.0']
    attributes:
      percona:
        master: '192.168.0.23'
        slaves: ['192.168.0.24']

  - name: master
    driver:
      vm_hostname: master-cent6
      network:
      - ['private_network', {ip: '192.168.0.25'}]
    run_list:
    - recipe[percona-multi::master]
    excludes: ['ubuntu-12.04', 'ubuntu-14.04', 'centos-7.0']
    attributes:
      percona:
        master: '192.168.0.25'
        slaves: ['192.168.0.26']

  - name: slave
    driver:
      vm_hostname: slave-cent6
      network:
      - ['private_network', {ip: '192.168.0.26'}]
    run_list:
    - recipe[percona-multi::slave]
    excludes: ['ubuntu-12.04', 'ubuntu-14.04', 'centos-7.0']
    attributes:
      percona:
        master: '192.168.0.25'
        slaves: ['192.168.0.26']

  - name: master
    driver:
      vm_hostname: master-cent7
      network:
      - ['private_network', {ip: '192.168.0.27'}]
    run_list:
    - recipe[percona-multi::master]
    excludes: ['ubuntu-12.04', 'centos-6.5', 'ubuntu-14.04']
    attributes:
      percona:
        master: '192.168.0.27'
        slaves: ['192.168.0.28']

  - name: slave
    driver:
      vm_hostname: slave-cent7
      network:
      - ['private_network', {ip: '192.168.0.28'}]
    run_list:
    - recipe[percona-multi::slave]
    excludes: ['ubuntu-12.04', 'centos-6.5', 'ubuntu-14.04']
    attributes:
      percona:
        master: '192.168.0.27'
        slaves: ['192.168.0.28']
