---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

driver_config:
  require_chef_omnibus: latest

provisioner:
  name: chef_solo
  client_rb:
    environment: _default
  attributes:
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
      omnibus_updater:
        enabled: false
      iptables:
        allow_ssh_from_world: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'sekrit'
    percona:
      master: '1.2.3.4'
      slaves: ['5.6.7.8']
      skip_passwords: true
      apt_keyserver: 'hkp://keys.gnupg.net'
      server:
        includedir: '/etc/mysql/conf.d/'
        replication:
          password: 'test123'

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: master
    run_list: recipe[percona-multi::master]
    attributes:

  - name: slave
    run_list: recipe[percona-multi::slave]
    attributes:
